### ISSUE TITLE
Add MLTK to Maven Central

### ISSUE THREAD

**Issue by sbelak** [yinlou/mltk#18]
I'm using MLTK from Clojure and deployment/installation of code dependent on it would be much nicer if it were in [Maven Central](https://search.maven.org/).

**Comment by yinlou** [comment]
Now you can get it from maven central:
```
<dependency>
  <groupId>com.github.yinlou</groupId>
  <artifactId>mltk</artifactId>
  <version>0.1.0</version>
</dependency>
```
